<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?>

ERROR - 05-06-2015 15:57:03 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 15:57:04 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 15:57:17 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 15:57:17 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 15:57:24 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 15:57:25 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 15:57:26 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:36:33 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:36:35 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:36:35 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:37:11 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:37:12 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:37:13 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:37:13 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:37:13 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:39:17 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:39:19 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:39:19 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:42:37 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:42:39 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:42:39 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:42:40 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:42:43 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:42:43 --> Severity: Notice  --> Undefined property: CI::$IDUser D:\xampp\htdocs\timesheet\system\core\Model.php 51
ERROR - 05-06-2015 16:42:43 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:42:50 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:42:55 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 05-06-2015 16:43:01 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
