<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?>

ERROR - 04-07-2015 04:57:55 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:11 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:12 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:17 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:18 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:19 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:24 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:27 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:28 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:28 --> tgl awal01-05-2015
ERROR - 04-07-2015 04:58:28 --> tgl akhir04-07-2015
ERROR - 04-07-2015 04:58:28 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:36 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:42 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:45 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:46 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:46 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:47 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:58:52 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:59:01 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:59:08 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:59:22 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:59:26 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:59:31 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:59:32 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:59:38 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:59:40 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:59:40 --> tgl awal01-05-2015
ERROR - 04-07-2015 04:59:40 --> tgl akhir04-07-2015
ERROR - 04-07-2015 04:59:40 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:59:44 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:59:46 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 04:59:46 --> tgl awal01-05-2015
ERROR - 04-07-2015 04:59:46 --> tgl akhir04-07-2015
ERROR - 04-07-2015 04:59:47 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:02 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:09 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:16 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:17 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:25 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:25 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:31 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:31 --> Severity: Warning  --> Missing argument 2 for Timesheet::GetDaftarTimesheet() D:\xampp\htdocs\timesheet\timesheet_application\modules\timesheet\controllers\timesheet.php 367
ERROR - 04-07-2015 05:00:31 --> Severity: Notice  --> Undefined variable: tglAkhir D:\xampp\htdocs\timesheet\timesheet_application\modules\timesheet\controllers\timesheet.php 374
ERROR - 04-07-2015 05:00:31 --> Severity: Notice  --> Undefined offset: 2 D:\xampp\htdocs\timesheet\timesheet_application\helpers\func_helper.php 128
ERROR - 04-07-2015 05:00:31 --> Severity: Notice  --> Undefined offset: 1 D:\xampp\htdocs\timesheet\timesheet_application\helpers\func_helper.php 129
ERROR - 04-07-2015 05:00:36 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:40 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:41 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:42 --> tgl awal01-04-2015
ERROR - 04-07-2015 05:00:42 --> tgl akhir04-07-2015
ERROR - 04-07-2015 05:00:42 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:46 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:48 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:00:48 --> tgl awal01-04-2015
ERROR - 04-07-2015 05:00:48 --> tgl akhir04-07-2015
ERROR - 04-07-2015 05:00:48 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:01:30 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:01:31 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:01:32 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:01:40 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:01:48 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:01:54 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:02:02 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:02:03 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:02:09 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:02:09 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:04:53 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:04:54 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:04:55 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:05:01 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:05:05 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:05:11 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:05:20 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:05:20 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:06:20 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:06:21 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:06:23 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:06:24 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:06:25 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:06:31 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:06:35 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:06:41 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:06:49 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:06:49 --> tgl awal04-07-2015
ERROR - 04-07-2015 05:06:49 --> tgl akhir04-07-2015
ERROR - 04-07-2015 05:06:49 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:08:42 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:08:45 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:08:46 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:08:50 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:08:50 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:08:56 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:09:00 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:09:07 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:09:15 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:09:16 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:09:28 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:09:28 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:13:02 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:13:04 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:13:05 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:13:11 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:13:18 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:13:19 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:27:51 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:27:59 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:27:59 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:28:02 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:28:03 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:28:03 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:28:12 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:28:14 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:28:14 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:28:47 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:28:57 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 04-07-2015 05:28:57 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
