<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?>

ERROR - 01-06-2015 17:55:43 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 17:55:43 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 17:55:56 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 17:55:57 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 17:56:00 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 17:56:01 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 17:56:02 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 17:56:05 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:12:23 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:12:25 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:12:26 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:12:27 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:12:29 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:12:29 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:12:36 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:12:37 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:27:23 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:27:24 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:27:25 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:27:26 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:27:26 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
ERROR - 01-06-2015 18:27:27 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead D:\xampp\htdocs\timesheet\system\database\drivers\mysql\mysql_driver.php 91
